H2.3 SVM for XOR pattern
========================

In [1]:
import numpy as np
from sklearn import svm
from math import sqrt

X = np.array([[-1, -1], [-1, 1], [1, -1], [1, 1]])
y = np.array([[1], [-1], [-1], [1]])


### (a) Linearly separable?
First, generate a 2D kerenl function for mapping to 6D feature vector

In [115]:
def kernel_function(X):
    phi = np.zeros((4, 6))
    for i in range(4):
        phi[i] = [1, sqrt(2) * X[i, 0], sqrt(2) * X[i, 1], X[i, 0]**2, X[i, 1]**2, sqrt(2) * X[i, 0] * X[i, 1]]
    return phi

def regression(X, y):
#     w = np.array([[0], [0], [0], [0], [0], [0]])
    w = np.zeros(6)
    y_hat = 0.
    for i in range(4):
        h = np.dot(w, X[i])
        h = 0.
        if h > 0.:
            y_hat = 1.
        elif h < 0:
            y_hat = -1.
        error = y[i, 0] - y_hat
        w += np.dot(error, X[i])
    return w


In [116]:
Xt = kernel_function(X)
w = regression(Xt, y)
print(w)

[0.         0.         0.         0.         0.         5.65685425]


In [109]:
score = 0
for i in range(4):
    prediction = 1 if np.dot(w, Xt[i]) > 0 else -1
    if prediction == y[i, 0]:
        score += 1
print('separatable: {0}%'.format(score*100/len(y)))

separatable: 100.0%


### (b) G matrix

In [119]:
def generate_G(phi, y):
    G = np.zeros((4,4))
    for i in range(4):
        for j in range(4):
            G[i, j] = y[i,0] * y[j,0] * np.dot(phi[i,:], phi[j,:])
    return G

G = generate_G(Xt, y)
print("G = {0}".format(G))

G = [[ 9. -1. -1.  1.]
 [-1.  9.  1. -1.]
 [-1.  1.  9. -1.]
 [ 1. -1. -1.  9.]]


### (c) Alpha

In [120]:
G_inverse = np.linalg.inv(G)
alpha = np.dot(G_inverse, np.ones((4, 1)))
print("alpha = {0}".format(alpha))

alpha = [[0.125]
 [0.125]
 [0.125]
 [0.125]]


### (d) SVM

In [124]:
def svm_fit(X, y, alpha):
    w = np.zeros((6,1))
    for i in range(6):
        for j in range(4):
            w[i] = w[i] + alpha[j] * y[j, 0] * X[j, i]
    return w

def svm_predict(X, w, d):
    return np.dot(w.T, X[d])


In [125]:
weights = svm_fit(Xt, y, alpha)
print("SVM weights: {0}".format(weights))
svm_predict(Xt, weights, 2)

SVM weights: [[ 0.00000000e+00]
 [ 0.00000000e+00]
 [-5.55111512e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 7.07106781e-01]]


array([-1.])